<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'Invalid item ID' => 'معرف عنصر غير صالح',
	"Item added to wishlist Successfully" => 'تمت إضافة العنصر إلى قائمة الرغبات بنجاح',
	"Error While Adding Item To Wishlist" => 'حدث خطأ أثناء إضافة عنصر إلى قائمة المفضلات',
	"Item Already Added" => 'العنصر تمت إضافته بالفعل',
	"Please login to add item to wishlist" => 'الرجاء تسجيل الدخول لإضافة عنصر إلى قائمة الرغبات',
	"Invalid Wishlist ID" => 'معرف قائمة الأمنيات غير صالح',
	"Item remove from wishlist successfully" => 'إزالة العنصر من المفضلة بنجاح',
	"Error While Deleting Item From Wishlist" => 'حدث خطأ أثناء حذف العنصر من قائمة المفضلات',
	"Profile updated successfully." => "تم تحديث الملف الشخصي بنجاح.",
	"Invalid Profile." => "الملف الشخصي غير صالح.",
	"Mail sent successfully" => "تم إرسال البريد بنجاح",
	"Please click the verification link sent to you by email to activate your account" => "يرجى النقر على رابط التحقق الذي تم إرساله إليك عبر البريد الإلكتروني لتنشيط حسابك",
	"User logged out successfully" => "تم تسجيل خروج المستخدم بنجاح",
	"Error with User logged out. Please try again." => "حدث خطأ أثناء تسجيل خروج المستخدم. حاول مرة اخرى.",
	"Please provide answer of question {question}" => "يرجى تقديم الإجابة عن السؤال {كيستيون}",
	"Address Saved Successfully" => "تم حفظ العنوان بنجاح",
	"Error While Saving Address" => "حدث خطأ أثناء حفظ العنوان",
	"Address Updated Successfully" => "تم تحديث العنوان بنجاح",
	"Error While Updating Address" => "حدث خطأ أثناء تحديث العنوان",
	"Unable To Find Address With Address ID" => "تعذر العثور على العنوان باستخدام معرف العنوان",
	"Address Deleted Successfully" => "تم حذف العنوان بنجاح",
	"Address Doesn't exist" => "العنوان غير موجود",
	"Welcome to The White Book" => "مرحبا بكم في الكتاب الأبيض",
	"Please click on the link sent to you by email to verify your account" => "يرجى النقر على الرابط المرسل إليك عن طريق البريد الإلكتروني للتحقق من حسابك",
	"Invalid Email" => "بريد إلكتروني خاطئ",
	"Requested forgot Password" => "طلب نسيت كلمة المرور",
	"Password reset link sent, please check your email for further instructions." => "تم إرسال رابط إعادة تعيين كلمة المرور، يرجى التحقق من بريدك الإلكتروني للحصول على مزيد من الإرشادات.",
	"Server issue. Please try again" => "مشكلة الخادم. حاول مرة اخرى",
	"Email Does Not Exist" => "البريد الإلكتروني غير موجود",
	"Booking not found" => "لم يتم العثور على الحجز"
	'Success: Product <a href="{product_link}">{product_name}</a> updated in cart successfully' => "النجاح: تم تحديث المنتج <a href="{product_link}"> {product_name} </a> في سلة التسوق بنجاح",
	"Error while updateing cart" => "حدث خطأ أثناء تحديث العربة",
	"Invalid Item ID" => "معرف العنصر غير صالح",
	"Invalid Time Slot" => "فترة زمنية غير صالحة",
	"Invalid Delivery Date" => "تاريخ التسليم غير صالح",
	"Invalid Quantity" => "كمية غير صالحة",
	"Invalid Area" => "منطقة غير صالحة",
	"Item added to cart successfully" => "تمت إضافة العنصر إلى سلة التسوق بنجاح",
	"Cart Item Deleted Successfully" => "تم حذف عنصر السلة بنجاح",
	"Invalid Cart ID" => "معرف سلة التسوق غير صالح",
	"Can not proceed as cart item(s) not valid" => "لا يمكن المتابعة كعنصر (عناصر) سلة التسوق غير صالح",
	"Order Successfully Completed" => "تم إكمال الطلب بنجاح",
	"Customer info missing" => "معلومات العميل في عداد المفقودين",
	"Area not found" => "لم يتم العثور على المنطقة",
	"Event Already Exist With Same Name." => "حدث بالفعل موجود مع نفس الاسم.",
	"Delivery info missing" => "معلومات التسليم في عداد المفقودين",
	"Event Created Successfully." => "تم إنشاء الحدث بنجاح.",
	"Error While Saving Error." => "حدث خطأ أثناء حفظ الخطأ.",
	"Empty event fields." => "حقول الحدث الفارغ.",
	"Invalid Event." => "حدث غير صالح.",
	"Event Saved Successfully." => "تم حفظ الحدث بنجاح.",
	"Invalid Event ID." => "معرف الحدث غير صالح.",
	"Event Deleted Successfully." => "تم حذف الحدث بنجاح.",
	"{count} week(s)" => "{كونت} أسبوع (أسابيع)",
	"{count} day(s)" => "{كونت} يوم (أيام)",
	"{count} hours" => "{كونت} ساعة",
	"{item_name} already exist with {event_name}" => "{item_name} موجود بالفعل مع {event_name}",
	"{item_name} has been added to {event_name}" => "تمت إضافة {item_name} إلى {event_name}",
	"Invalid Vendor ID" => "معرف المورد غير صالح",
	"Invalid Event Date" => "تاريخ الحدث غير صالح",
	"Payment was declined by Tap" => "تم رفض الدفعة عن طريق النقر",
	"Unable to locate or update your booking status" => "تعذر تحديد مكان حالة الحجز أو تحديثها"
];